# docker-compose.yml

version: '3.8'

services:
  database:
    build: ./database
    restart: unless-stopped
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fina
      POSTGRES_DB: fina
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]
      interval: 5s
      start_period: 5s
      timeout: 20s
      retries: 3
    ports:
      - 127.0.0.1:5432:5432
  api:
    build: ./api
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      POSTGRES_URL: postgresql://postgres:fina@database:5432/fina
      DEBUG: 1
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./api/app
        target: /code/app
        read_only: true
    ports:
      - 127.0.0.1:8080:8080